version: '2.1'
services:
  appdaemon:
    image: acockburn/appdaemon:3.0.1
    container_name: appdaemon
    restart: always
#    network_mode: 'host'
    ports:
      - '5050:5050'
    volumes:
      - '/home/jamie/ha-dashboard:/conf'

# JRS-TMP hadash:
# JRS-TMP   build: 'hadashboard/'
# JRS-TMP   ports:
# JRS-TMP     - '3030:3030'
# JRS-TMP   environment:
# JRS-TMP     - 'TZ=America/New_York'
# JRS-TMP   volumes:
# JRS-TMP     - './config/hadash/dashboards:/app/dashboards'
# JRS-TMP     - './config/hadash/ha_conf.rb:/app/lib/ha_conf.rb'
# JRS-TMP     - './config/hadash/hapush.cfg:/app/hapush/hapush.cfg'
