services:
  appdaemon:
    image: acockburn/appdaemon:4.4.2
    container_name: ha-dashboard
    restart: always
    ports:
      - '5050:5050'
    volumes:
      - './:/conf'
      - './certs:/certs'

    env_file: .env
    
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.appdaemon.rule=Host(`${TRAEFIK_HOST}`)"
      - "traefik.http.routers.appdaemon.entrypoints=https"
      - "traefik.http.routers.appdaemon.tls=true"
      - "traefik.http.routers.appdaemon.tls.certresolver=cloudflare"
      - "traefik.http.services.appdaemon.loadbalancer.server.port=5050"

    networks:
      - traefik
networks:
  traefik:
    external: true
